/**
 * Catálogo Curado Oficial de Exercícios Biomecânicos do AppNutri (ETAPA 7)
 * Dados estruturados, estritos e versionados (WORKOUT_ENGINE_VERSION = '1.0.0').
 * ZERO claims médicos. Classificação puramente cineantropométrica e biomecânica.
 * Restrições de movimento padronizadas como flags estruturais (evita diagnósticos clínicos automáticos a partir de sintomas).
 */

import crypto from 'crypto';
import { Exercise } from '@/types/workout-engine';

export const EXERCISE_CATALOG_VERSION = '1.0.0';
export const EXERCISE_CATALOG_SCHEMA_VERSION = '1.0.0';
export const EXERCISE_CATALOG_PROVENANCE = 'AppNutri Curated Biomechanical Catalog (Internal Review v1.0.0)';

export const CURATED_EXERCISE_CATALOG: Exercise[] = [
  // ============================================================================
  // 1. SQUAT (Agachamento / Dominância de Joelho)
  // ============================================================================
  {
    id: 'ex-squat-001',
    code: 'BARBELL_BACK_SQUAT',
    name: 'Agachamento Livre com Barra',
    normalized_name: 'agachamento livre com barra',
    aliases: ['back squat', 'agachamento costas', 'barbell squat'],
    movement_pattern: 'squat',
    primary_muscle_groups: ['quadriceps', 'glutes'],
    secondary_muscle_groups: ['hamstrings', 'core', 'calves'],
    required_equipment: ['barbell'],
    complexity_level: 'intermediate',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_axial_spinal_loading', 'avoid_deep_knee_flexion'],
    instructions: 'Posicione a barra sobre o trapézio, pés na largura dos ombros. Flexione quadril e joelhos mantendo o tronco firme até que as coxas fiquem paralelas ao solo.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-squat-002',
    code: 'GOBLET_SQUAT_DUMBBELL',
    name: 'Agachamento Goblet com Halter',
    normalized_name: 'agachamento goblet com halter',
    aliases: ['goblet squat', 'agachamento com halter frontal'],
    movement_pattern: 'squat',
    primary_muscle_groups: ['quadriceps', 'glutes'],
    secondary_muscle_groups: ['core'],
    required_equipment: ['dumbbell'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_deep_knee_flexion'],
    instructions: 'Segure um halter verticalmente próximo ao peito com ambas as mãos. Agache mantendo a coluna alinhada e cotovelos por dentro dos joelhos.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-squat-003',
    code: 'LEG_PRESS_45',
    name: 'Leg Press 45°',
    normalized_name: 'leg press 45',
    aliases: ['leg press', 'leg 45'],
    movement_pattern: 'squat',
    primary_muscle_groups: ['quadriceps', 'glutes'],
    secondary_muscle_groups: ['hamstrings', 'calves'],
    required_equipment: ['machine'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_deep_hip_flexion_under_load'],
    instructions: 'Apoie as costas completamente no encosto e posicione os pés na plataforma na largura dos ombros. Destrave o aparelho e flexione os joelhos a 90 graus sem tirar a lombar do apoio.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-squat-004',
    code: 'BODYWEIGHT_SQUAT',
    name: 'Agachamento Livre com Peso Corporal',
    normalized_name: 'agachamento livre com peso corporal',
    aliases: ['air squat', 'agachamento corporal'],
    movement_pattern: 'squat',
    primary_muscle_groups: ['quadriceps', 'glutes'],
    secondary_muscle_groups: ['core'],
    required_equipment: ['bodyweight'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Com os pés afastados na largura dos quadris, agache com controle mantendo os calcanhares no chão e braços estendidos à frente para equilíbrio.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-squat-005',
    code: 'HACK_SQUAT_MACHINE',
    name: 'Hack Squat na Máquina',
    normalized_name: 'hack squat na maquina',
    aliases: ['agachamento hack', 'hack machine'],
    movement_pattern: 'squat',
    primary_muscle_groups: ['quadriceps'],
    secondary_muscle_groups: ['glutes', 'calves'],
    required_equipment: ['machine'],
    complexity_level: 'intermediate',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_deep_knee_flexion'],
    instructions: 'Posicione os ombros e costas nas almofadas do hack. Desça de forma controlada enfatizando a flexão dos joelhos e empurre pela planta dos pés.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },

  // ============================================================================
  // 2. HINGE (Dobradiça de Quadril / Posterior e Glúteos)
  // ============================================================================
  {
    id: 'ex-hinge-001',
    code: 'ROMANIAN_DEADLIFT_BARBELL',
    name: 'Levantamento Terra Romeno com Barra (RDL)',
    normalized_name: 'levantamento terra romeno com barra rdl',
    aliases: ['rdl barra', 'romanian deadlift', 'stiff com barra'],
    movement_pattern: 'hinge',
    primary_muscle_groups: ['hamstrings', 'glutes'],
    secondary_muscle_groups: ['back', 'core', 'forearms'],
    required_equipment: ['barbell'],
    complexity_level: 'intermediate',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_axial_spinal_loading'],
    instructions: 'Em pé segurando a barra na largura dos ombros, empurre o quadril para trás mantendo os joelhos semi-flexionados e coluna neutra até sentir os isquiotibiais alongarem.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-hinge-002',
    code: 'ROMANIAN_DEADLIFT_DUMBBELL',
    name: 'Levantamento Terra Romeno com Halteres',
    normalized_name: 'levantamento terra romeno com halteres',
    aliases: ['rdl halteres', 'dumbbell rdl', 'stiff halteres'],
    movement_pattern: 'hinge',
    primary_muscle_groups: ['hamstrings', 'glutes'],
    secondary_muscle_groups: ['core', 'forearms'],
    required_equipment: ['dumbbell'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_axial_spinal_loading'],
    instructions: 'Segure os halteres ao lado das coxas. Incline o tronco para a frente empurrando os quadris para trás, descendo os halteres rente às pernas.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-hinge-003',
    code: 'CONVENTIONAL_DEADLIFT',
    name: 'Levantamento Terra Convencional',
    normalized_name: 'levantamento terra convencional',
    aliases: ['deadlift', 'terra'],
    movement_pattern: 'hinge',
    primary_muscle_groups: ['back', 'glutes', 'hamstrings'],
    secondary_muscle_groups: ['quadriceps', 'forearms', 'core'],
    required_equipment: ['barbell'],
    complexity_level: 'advanced',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_axial_spinal_loading', 'avoid_heavy_floor_pulls'],
    instructions: 'Posicione a barra sobre o meio dos pés. Agache ligeiramente segurando a barra com pegada pronada ou mista e erga o peso com extensão síncrona de quadril e joelhos.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-hinge-004',
    code: 'BARBELL_HIP_THRUST',
    name: 'Elevação Pélvica com Barra (Hip Thrust)',
    normalized_name: 'elevacao pelvica com barra hip thrust',
    aliases: ['hip thrust', 'elevacao pelvica no banco'],
    movement_pattern: 'hinge',
    primary_muscle_groups: ['glutes'],
    secondary_muscle_groups: ['hamstrings', 'core'],
    required_equipment: ['barbell', 'bench'],
    complexity_level: 'intermediate',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Apoie a região escapular num banco plano, com a barra acolchoada sobre os quadris. Eleve a pelve contraindo fortemente os glúteos no topo da amplitude.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-hinge-005',
    code: 'DUMBBELL_GLUTE_BRIDGE',
    name: 'Ponte de Glúteos no Solo com Halter',
    normalized_name: 'ponte de gluteos no solo com halter',
    aliases: ['glute bridge halter', 'elevacao pelvica solo'],
    movement_pattern: 'hinge',
    primary_muscle_groups: ['glutes'],
    secondary_muscle_groups: ['hamstrings'],
    required_equipment: ['dumbbell'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Deitado de costas com joelhos dobrados, apoie um halter sobre o quadril e empurre pelos calcanhares até alinhar joelhos, quadris e ombros.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },

  // ============================================================================
  // 3. PUSH HORIZONTAL (Empurrar Horizontal / Peitoral, Deltóide Anterior, Tríceps)
  // ============================================================================
  {
    id: 'ex-push-h-001',
    code: 'BARBELL_BENCH_PRESS',
    name: 'Supino Reto com Barra',
    normalized_name: 'supino reto com barra',
    aliases: ['bench press', 'supino reto'],
    movement_pattern: 'push_horizontal',
    primary_muscle_groups: ['chest'],
    secondary_muscle_groups: ['shoulders', 'triceps'],
    required_equipment: ['barbell', 'bench'],
    complexity_level: 'intermediate',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_extreme_horizontal_abduction'],
    instructions: 'Deite no banco reto, segure a barra com pegada ligeiramente além dos ombros. Desça a barra de forma controlada até tocar suavemente o meio do tórax e empurre para cima.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-push-h-002',
    code: 'DUMBBELL_BENCH_PRESS',
    name: 'Supino Reto com Halteres',
    normalized_name: 'supino reto com halteres',
    aliases: ['dumbbell bench press', 'supino com halteres'],
    movement_pattern: 'push_horizontal',
    primary_muscle_groups: ['chest'],
    secondary_muscle_groups: ['shoulders', 'triceps'],
    required_equipment: ['dumbbell', 'bench'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_extreme_horizontal_abduction'],
    instructions: 'No banco plano, inicie com os halteres estendidos acima do peito. Flexione os cotovelos a cerca de 45 a 70 graus descendo até alongar o peitoral e retorne.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-push-h-003',
    code: 'INCLINE_DUMBBELL_PRESS',
    name: 'Supino Inclinado com Halteres',
    normalized_name: 'supino inclinado com halteres',
    aliases: ['incline dumbbell press', 'supino inclinado halteres'],
    movement_pattern: 'push_horizontal',
    primary_muscle_groups: ['chest', 'shoulders'],
    secondary_muscle_groups: ['triceps'],
    required_equipment: ['dumbbell', 'bench'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_extreme_horizontal_abduction'],
    instructions: 'Regule o banco a 30-45 graus. Pressione os halteres para cima a partir da linha dos ombros, focando a porção clavicular do peitoral.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-push-h-004',
    code: 'PUSH_UP',
    name: 'Flexão de Braços no Solo',
    normalized_name: 'flexao de bracos no solo',
    aliases: ['push up', 'apoio de frente'],
    movement_pattern: 'push_horizontal',
    primary_muscle_groups: ['chest'],
    secondary_muscle_groups: ['shoulders', 'triceps', 'core'],
    required_equipment: ['bodyweight'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_wrist_extension_loading'],
    instructions: 'Em posição de prancha alta com as mãos alinhadas com o peito, flexione os cotovelos aproximando o peito do solo e empurre até a extensão quase completa.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-push-h-005',
    code: 'MACHINE_CHEST_PRESS',
    name: 'Supino Sentado na Máquina',
    normalized_name: 'supino sentado na maquina',
    aliases: ['chest press machine', 'supino maquina'],
    movement_pattern: 'push_horizontal',
    primary_muscle_groups: ['chest'],
    secondary_muscle_groups: ['triceps', 'shoulders'],
    required_equipment: ['machine'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Ajuste a altura do banco para que as manoplas fiquem na linha média do peito. Empurre as alavancas à frente sem travar bruscamente os cotovelos.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },

  // ============================================================================
  // 4. PUSH VERTICAL (Empurrar Vertical / Ombros e Tríceps)
  // ============================================================================
  {
    id: 'ex-push-v-001',
    code: 'OVERHEAD_BARBELL_PRESS',
    name: 'Desenvolvimento Militar com Barra em Pé',
    normalized_name: 'desenvolvimento militar com barra em pe',
    aliases: ['overhead press', 'militar', 'ohp'],
    movement_pattern: 'push_vertical',
    primary_muscle_groups: ['shoulders'],
    secondary_muscle_groups: ['triceps', 'core'],
    required_equipment: ['barbell'],
    complexity_level: 'advanced',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_overhead_movement', 'avoid_axial_spinal_loading'],
    instructions: 'Em pé com o abdômen travado e glúteos contraídos, pressione a barra a partir da clavícula verticalmente até estender os braços sobre a cabeça.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-push-v-002',
    code: 'SEATED_DUMBBELL_SHOULDER_PRESS',
    name: 'Desenvolvimento com Halteres Sentado',
    normalized_name: 'desenvolvimento com halteres sentado',
    aliases: ['dumbbell shoulder press', 'desenvolvimento halteres'],
    movement_pattern: 'push_vertical',
    primary_muscle_groups: ['shoulders'],
    secondary_muscle_groups: ['triceps'],
    required_equipment: ['dumbbell', 'bench'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_overhead_movement'],
    instructions: 'Sentado num banco com apoio a 80-85 graus, eleve os halteres a partir da linha das orelhas até o topo sem colidir os pesos.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-push-v-003',
    code: 'MACHINE_SHOULDER_PRESS',
    name: 'Desenvolvimento de Ombros na Máquina',
    normalized_name: 'desenvolvimento de ombros na maquina',
    aliases: ['shoulder press machine', 'desenvolvimento maquina'],
    movement_pattern: 'push_vertical',
    primary_muscle_groups: ['shoulders'],
    secondary_muscle_groups: ['triceps'],
    required_equipment: ['machine'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_overhead_movement'],
    instructions: 'Ajuste o assento para que as manoplas comecem na altura dos ombros. Empurre para cima com movimento guiado e seguro.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-push-v-004',
    code: 'DUMBBELL_LATERAL_RAISE',
    name: 'Elevação Lateral com Halteres',
    normalized_name: 'elevacao lateral com halteres',
    aliases: ['lateral raise', 'elevacao lateral'],
    movement_pattern: 'push_vertical',
    primary_muscle_groups: ['shoulders'],
    secondary_muscle_groups: ['forearms'],
    required_equipment: ['dumbbell'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: [],
    instructions: 'Em pé, eleve os halteres lateralmente no plano escapular até a altura dos ombros mantendo ligeira flexão de cotovelo.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-push-v-005',
    code: 'CABLE_LATERAL_RAISE',
    name: 'Elevação Lateral no Cabo / Polia',
    normalized_name: 'elevacao lateral no cabo polia',
    aliases: ['cable lateral raise', 'lateral no cross'],
    movement_pattern: 'push_vertical',
    primary_muscle_groups: ['shoulders'],
    secondary_muscle_groups: [],
    required_equipment: ['cable'],
    complexity_level: 'beginner',
    is_unilateral: true,
    is_compound: false,
    safety_contraindications: [],
    instructions: 'Com a polia na altura do joelho ou tornozelo, puxe a manopla lateralmente garantindo tensão contínua em todo o arco do movimento.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },

  // ============================================================================
  // 5. PULL HORIZONTAL (Puxar Horizontal / Dorsal, Trapézio, Romboide, Bíceps)
  // ============================================================================
  {
    id: 'ex-pull-h-001',
    code: 'BARBELL_BENT_OVER_ROW',
    name: 'Remada Curvada com Barra',
    normalized_name: 'remada curvada com barra',
    aliases: ['bent over row', 'remada curvada barra'],
    movement_pattern: 'pull_horizontal',
    primary_muscle_groups: ['back'],
    secondary_muscle_groups: ['biceps', 'forearms', 'core'],
    required_equipment: ['barbell'],
    complexity_level: 'intermediate',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_axial_spinal_loading'],
    instructions: 'Com o tronco inclinado a aproximadamente 45 graus e coluna neutra, puxe a barra em direção ao umbigo aproximando as escápulas.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-pull-h-002',
    code: 'DUMBBELL_SINGLE_ARM_ROW',
    name: 'Remada Unilateral com Halter (Serrote)',
    normalized_name: 'remada unilateral com halter serrote',
    aliases: ['dumbbell row', 'remada serrote'],
    movement_pattern: 'pull_horizontal',
    primary_muscle_groups: ['back'],
    secondary_muscle_groups: ['biceps', 'forearms'],
    required_equipment: ['dumbbell', 'bench'],
    complexity_level: 'beginner',
    is_unilateral: true,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Apoie um joelho e a mão ipsilateral no banco. Com o outro braço, puxe o halter rente ao quadril focando a retração escapular.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-pull-h-003',
    code: 'SEATED_CABLE_ROW',
    name: 'Remada Baixa Sentada no Cabo',
    normalized_name: 'remada baixa sentada no cabo',
    aliases: ['seated cable row', 'remada baixa triângulo'],
    movement_pattern: 'pull_horizontal',
    primary_muscle_groups: ['back'],
    secondary_muscle_groups: ['biceps', 'forearms'],
    required_equipment: ['cable'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Sentado com os joelhos ligeiramente destravados, puxe o pegador triângulo em direção ao abdômen mantendo o peito aberto.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-pull-h-004',
    code: 'CHEST_SUPPORTED_MACHINE_ROW',
    name: 'Remada Máquina com Apoio no Peito',
    normalized_name: 'remada maquina com apoio no peito',
    aliases: ['machine row', 'remada articulada'],
    movement_pattern: 'pull_horizontal',
    primary_muscle_groups: ['back'],
    secondary_muscle_groups: ['biceps', 'forearms'],
    required_equipment: ['machine'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Apoie o esterno na almofada frontal para isolar a musculatura dorsal eliminando a sobrecarga de estabilização lombar.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },

  // ============================================================================
  // 6. PULL VERTICAL (Puxar Vertical / Grande Dorsal, Redondo Maior, Bíceps)
  // ============================================================================
  {
    id: 'ex-pull-v-001',
    code: 'PULL_UP',
    name: 'Barra Fixa com Pegada Pronada',
    normalized_name: 'barra fixa com pegada pronada',
    aliases: ['pull up', 'barra fixa'],
    movement_pattern: 'pull_vertical',
    primary_muscle_groups: ['back'],
    secondary_muscle_groups: ['biceps', 'forearms', 'core'],
    required_equipment: ['pull_up_bar', 'bodyweight'],
    complexity_level: 'advanced',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_overhead_hanging_traction'],
    instructions: 'Segure a barra com pegada pronada ligeiramente além dos ombros. Tracione o corpo até que o queixo passe a barra.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-pull-v-002',
    code: 'LAT_PULLDOWN_WIDE_GRIP',
    name: 'Puxada Alta com Barra no Cabo (Pegada Aberta)',
    normalized_name: 'puxada alta com barra no cabo pegada aberta',
    aliases: ['lat pulldown', 'puxada aberta'],
    movement_pattern: 'pull_vertical',
    primary_muscle_groups: ['back'],
    secondary_muscle_groups: ['biceps', 'forearms'],
    required_equipment: ['cable'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Sentado com as coxas fixas sob os apoios, puxe a barra longa em direção à parte superior do tórax inclinando levemente o tronco.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-pull-v-003',
    code: 'LAT_PULLDOWN_NEUTRAL_GRIP',
    name: 'Puxada Alta com Pegada Triângulo / Neutra',
    normalized_name: 'puxada alta com pegada triangulo neutra',
    aliases: ['neutral lat pulldown', 'puxada triangulo'],
    movement_pattern: 'pull_vertical',
    primary_muscle_groups: ['back'],
    secondary_muscle_groups: ['biceps', 'forearms'],
    required_equipment: ['cable'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Utilizando o puxador triângulo, puxe verticalmente rente ao queixo facilitando o conforto articular de punho e cotovelo.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },

  // ============================================================================
  // 7. LUNGE (Afundo / Unilateral de Membros Inferiores)
  // ============================================================================
  {
    id: 'ex-lunge-001',
    code: 'BULGARIAN_SPLIT_SQUAT_DUMBBELL',
    name: 'Agachamento Búlgaro com Halteres',
    normalized_name: 'agachamento bulgaro com halteres',
    aliases: ['bulgarian split squat', 'agachamento bulgaro'],
    movement_pattern: 'lunge',
    primary_muscle_groups: ['quadriceps', 'glutes'],
    secondary_muscle_groups: ['hamstrings', 'calves', 'core'],
    required_equipment: ['dumbbell', 'bench'],
    complexity_level: 'intermediate',
    is_unilateral: true,
    is_compound: true,
    safety_contraindications: ['avoid_deep_knee_flexion'],
    instructions: 'Apoie o peito de um pé num banco atrás de você. Flexione a perna da frente até que a coxa fique quase paralela ao solo e empurre.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-lunge-002',
    code: 'WALKING_LUNGE_DUMBBELL',
    name: 'Passada / Afundo Caminhando com Halteres',
    normalized_name: 'passada afundo caminhando com halteres',
    aliases: ['walking lunge', 'passada halteres'],
    movement_pattern: 'lunge',
    primary_muscle_groups: ['quadriceps', 'glutes'],
    secondary_muscle_groups: ['hamstrings', 'calves'],
    required_equipment: ['dumbbell'],
    complexity_level: 'intermediate',
    is_unilateral: true,
    is_compound: true,
    safety_contraindications: ['avoid_dynamic_impact_loading'],
    instructions: 'Dê passos à frente flexionando ambos os joelhos a 90 graus de forma alternada e contínua.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-lunge-003',
    code: 'BODYWEIGHT_REVERSE_LUNGE',
    name: 'Afundo Reverso com Peso Corporal',
    normalized_name: 'afundo reverso com peso corporal',
    aliases: ['reverse lunge', 'afundo para tras'],
    movement_pattern: 'lunge',
    primary_muscle_groups: ['quadriceps', 'glutes'],
    secondary_muscle_groups: ['calves'],
    required_equipment: ['bodyweight'],
    complexity_level: 'beginner',
    is_unilateral: true,
    is_compound: true,
    safety_contraindications: [],
    instructions: 'Dê um passo para trás descendo o joelho posterior em direção ao solo com desaceleração controlada.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },

  // ============================================================================
  // 8. CARRY (Transporte de Cargas / Estabilização)
  // ============================================================================
  {
    id: 'ex-carry-001',
    code: 'FARMERS_WALK_DUMBBELL',
    name: 'Caminhada do Fazendeiro com Halteres (Farmer Walk)',
    normalized_name: 'caminhada do fazendeiro com halteres farmer walk',
    aliases: ['farmers walk', 'caminhada fazendeiro'],
    movement_pattern: 'carry',
    primary_muscle_groups: ['core', 'forearms'],
    secondary_muscle_groups: ['shoulders', 'calves'],
    required_equipment: ['dumbbell'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: true,
    safety_contraindications: ['avoid_axial_spinal_loading'],
    instructions: 'Segure halteres pesados ao lado do corpo, mantenha ombros para trás e caminhe com passos curtos e postura ereta.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },

  // ============================================================================
  // 9. CORE (Estabilização Central / Abdominais)
  // ============================================================================
  {
    id: 'ex-core-001',
    code: 'FOREARM_PLANK',
    name: 'Prancha Frontal no Solo (Isometria)',
    normalized_name: 'prancha frontal no solo isometria',
    aliases: ['plank', 'prancha ventral'],
    movement_pattern: 'core',
    primary_muscle_groups: ['core'],
    secondary_muscle_groups: ['shoulders', 'glutes'],
    required_equipment: ['bodyweight'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: [],
    instructions: 'Apoie antebraços e pontas dos pés no solo. Mantenha o corpo em linha reta e abdômen contraído sem deixar os quadris caírem.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-core-002',
    code: 'CABLE_WOODCHOPPER',
    name: 'Rotação de Tronco no Cabo (Woodchopper)',
    normalized_name: 'rotacao de tronco no cabo woodchopper',
    aliases: ['woodchopper', 'giro de tronco polia'],
    movement_pattern: 'core',
    primary_muscle_groups: ['core'],
    secondary_muscle_groups: ['shoulders'],
    required_equipment: ['cable'],
    complexity_level: 'intermediate',
    is_unilateral: true,
    is_compound: false,
    safety_contraindications: ['avoid_loaded_spinal_rotation'],
    instructions: 'Com a polia na altura média, segure a manopla com ambas as mãos e gire o tronco de forma controlada através da ação dos oblíquos.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-core-003',
    code: 'HANGING_KNEE_RAISE',
    name: 'Elevação de Joelhos na Barra Fixa',
    normalized_name: 'elevacao de joelhos na barra fixa',
    aliases: ['hanging knee raise', 'abdominal na barra'],
    movement_pattern: 'core',
    primary_muscle_groups: ['core'],
    secondary_muscle_groups: ['forearms'],
    required_equipment: ['pull_up_bar', 'bodyweight'],
    complexity_level: 'intermediate',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: ['avoid_overhead_hanging_traction'],
    instructions: 'Pendurado na barra com os braços estendidos, contraia o abdômen elevando os joelhos em direção ao peito sem balançar o corpo.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },

  // ============================================================================
  // 10. ISOLATION (Monoarticulares / Braços, Pernas, Ombros)
  // ============================================================================
  {
    id: 'ex-iso-001',
    code: 'BARBELL_BICEPS_CURL',
    name: 'Rosca Direta com Barra',
    normalized_name: 'rosca direta com barra',
    aliases: ['biceps curl', 'rosca direta'],
    movement_pattern: 'isolation',
    primary_muscle_groups: ['biceps'],
    secondary_muscle_groups: ['forearms'],
    required_equipment: ['barbell'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: [],
    instructions: 'Em pé, segure a barra com pegada supinada. Flexione os cotovelos elevando a barra sem movimentar excessivamente o tronco.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-iso-002',
    code: 'DUMBBELL_INCLINE_BICEPS_CURL',
    name: 'Rosca Bíceps Inclinada com Halteres',
    normalized_name: 'rosca biceps inclinada com halteres',
    aliases: ['incline dumbbell curl', 'rosca inclinada'],
    movement_pattern: 'isolation',
    primary_muscle_groups: ['biceps'],
    secondary_muscle_groups: ['forearms'],
    required_equipment: ['dumbbell', 'bench'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: [],
    instructions: 'Sentado num banco a 45-60 graus, execute a flexão de cotovelos permitindo o alongamento da cabeça longa do bíceps na fase excêntrica.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-iso-003',
    code: 'TRICEPS_ROPE_PUSHDOWN',
    name: 'Tríceps no Cabo com Corda',
    normalized_name: 'triceps no cabo com corda',
    aliases: ['rope pushdown', 'triceps corda'],
    movement_pattern: 'isolation',
    primary_muscle_groups: ['triceps'],
    secondary_muscle_groups: ['forearms'],
    required_equipment: ['cable'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: [],
    instructions: 'Com a polia alta e manopla de corda, empurre para baixo abrindo as pontas da corda na contração máxima mantendo os cotovelos junto ao tronco.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-iso-004',
    code: 'DUMBBELL_OVERHEAD_TRICEPS_EXTENSION',
    name: 'Tríceps Francês com Halter',
    normalized_name: 'triceps frances com halter',
    aliases: ['overhead triceps extension', 'triceps frances'],
    movement_pattern: 'isolation',
    primary_muscle_groups: ['triceps'],
    secondary_muscle_groups: [],
    required_equipment: ['dumbbell', 'bench'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: ['avoid_overhead_movement'],
    instructions: 'Segure um halter com ambas as mãos acima da cabeça. Flexione os cotovelos descendo o peso atrás da cabeça e estenda.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-iso-005',
    code: 'LEG_EXTENSION_MACHINE',
    name: 'Cadeira Extensora',
    normalized_name: 'cadeira extensora',
    aliases: ['leg extension', 'extensora'],
    movement_pattern: 'isolation',
    primary_muscle_groups: ['quadriceps'],
    secondary_muscle_groups: [],
    required_equipment: ['machine'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: ['avoid_open_chain_knee_extension'],
    instructions: 'Ajuste o apoio do rolo na tíbia logo acima dos tornozelos. Estenda os joelhos contraindo o quadríceps e retorne com velocidade controlada.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-iso-006',
    code: 'SEATED_LEG_CURL_MACHINE',
    name: 'Mesa / Cadeira Flexora (Isquiotibiais)',
    normalized_name: 'mesa cadeira flexora isquiotibiais',
    aliases: ['leg curl', 'flexora sentada', 'mesa flexora'],
    movement_pattern: 'isolation',
    primary_muscle_groups: ['hamstrings'],
    secondary_muscle_groups: ['calves'],
    required_equipment: ['machine'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: [],
    instructions: 'Sentado ou deitado conforme o aparelho, flexione os joelhos trazendo o rolo em direção aos glúteos.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-iso-007',
    code: 'STANDING_CALF_RAISE',
    name: 'Elevação de Panturrilha em Pé',
    normalized_name: 'elevacao de panturrilha em pe',
    aliases: ['calf raise', 'panturrilha em pe'],
    movement_pattern: 'isolation',
    primary_muscle_groups: ['calves'],
    secondary_muscle_groups: [],
    required_equipment: ['dumbbell'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: [],
    instructions: 'Com as pontas dos pés numa elevação ou no solo segurando halteres, eleve os calcanhares no ponto mais alto e desça alongando.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
  {
    id: 'ex-iso-008',
    code: 'FACE_PULL_CABLE',
    name: 'Face Pull no Cabo com Corda',
    normalized_name: 'face pull no cabo com corda',
    aliases: ['face pull', 'puxada para o rosto'],
    movement_pattern: 'isolation',
    primary_muscle_groups: ['shoulders', 'back'],
    secondary_muscle_groups: ['forearms'],
    required_equipment: ['cable'],
    complexity_level: 'beginner',
    is_unilateral: false,
    is_compound: false,
    safety_contraindications: [],
    instructions: 'Na polia na altura dos olhos, puxe a corda em direção à testa rotacionando externamente os ombros para fortalecimento dos retratores e manguito.',
    source_version: EXERCISE_CATALOG_VERSION,
    provenance: EXERCISE_CATALOG_PROVENANCE,
    is_active: true,
  },
];

/**
 * Serializador canônico que ordena recursivamente todas as chaves do objeto JSON.
 */
export function canonicalJsonStringifyCatalog(obj: unknown): string {
  if (obj === null || typeof obj !== 'object') {
    return JSON.stringify(obj);
  }
  if (Array.isArray(obj)) {
    return '[' + obj.map((item) => canonicalJsonStringifyCatalog(item)).join(',') + ']';
  }
  const keys = Object.keys(obj as Record<string, unknown>).sort();
  const pairs = keys.map((key) => {
    const value = (obj as Record<string, unknown>)[key];
    return JSON.stringify(key) + ':' + canonicalJsonStringifyCatalog(value);
  });
  return '{' + pairs.join(',') + '}';
}

/**
 * Calcula o checksum SHA-256 real e determinístico sobre o catálogo completo de exercícios.
 * Inclui todos os campos semanticamente relevantes:
 * - código/id canônico;
 * - nome;
 * - aliases relevantes;
 * - movement_pattern;
 * - primary_muscle_groups;
 * - secondary_muscle_groups;
 * - required_equipment;
 * - complexity_level;
 * - unilateral/bilateral;
 * - compound/isolation;
 * - tags estruturadas relevantes (safety_contraindications);
 * - schema/classification version.
 * Ordena deterministicamente os registros por id e os campos/listas antes do hash.
 */
export function computeCatalogChecksum(catalog: Exercise[] = CURATED_EXERCISE_CATALOG): string {
  // Ordena os exercícios deterministicamente por id para que a ordem da lista não afete o checksum
  const sortedExercises = [...catalog].sort((a, b) => a.id.localeCompare(b.id));

  const canonicalItems = sortedExercises.map((e) => ({
    aliases: [...(e.aliases ?? [])].sort(),
    code: e.code,
    complexity_level: e.complexity_level,
    id: e.id,
    is_compound: e.is_compound,
    is_unilateral: e.is_unilateral,
    movement_pattern: e.movement_pattern,
    name: e.name,
    primary_muscle_groups: [...e.primary_muscle_groups].sort(),
    required_equipment: [...e.required_equipment].sort(),
    safety_contraindications: [...(e.safety_contraindications ?? [])].sort(),
    schema_version: EXERCISE_CATALOG_SCHEMA_VERSION,
    secondary_muscle_groups: [...(e.secondary_muscle_groups ?? [])].sort(),
    source_version: e.source_version ?? EXERCISE_CATALOG_VERSION,
  }));

  const canonicalPayload = canonicalJsonStringifyCatalog({
    schema_version: EXERCISE_CATALOG_SCHEMA_VERSION,
    total_exercises: canonicalItems.length,
    exercises: canonicalItems,
  });

  return crypto.createHash('sha256').update(canonicalPayload, 'utf-8').digest('hex');
}

export const EXERCISE_CATALOG_CHECKSUM = computeCatalogChecksum(CURATED_EXERCISE_CATALOG);

/**
 * Calcula o snapshot hash estável de um exercício individual para auditoria histórica.
 */
export function computeExerciseSnapshotHash(exercise: Exercise): string {
  const snapshotData = {
    code: exercise.code,
    complexity_level: exercise.complexity_level,
    exercise_id: exercise.id,
    is_compound: exercise.is_compound,
    is_unilateral: exercise.is_unilateral,
    movement_pattern: exercise.movement_pattern,
    name: exercise.name,
    primary_muscle_groups: [...exercise.primary_muscle_groups].sort(),
    required_equipment: [...exercise.required_equipment].sort(),
    safety_contraindications: [...(exercise.safety_contraindications ?? [])].sort(),
    schema_version: EXERCISE_CATALOG_SCHEMA_VERSION,
    secondary_muscle_groups: [...(exercise.secondary_muscle_groups ?? [])].sort(),
    source_version: exercise.source_version ?? EXERCISE_CATALOG_VERSION,
  };
  return crypto.createHash('sha256').update(canonicalJsonStringifyCatalog(snapshotData), 'utf-8').digest('hex');
}
