-- ==============================================================================
-- MIGRATION: 20260907000006_invites_and_onboarding.sql
-- DESCRIPTION: Professional & Patient Invites, Patient Onboarding, and Safe RPC
-- ==============================================================================

-- 1. EXTEND PROFESSIONAL_PROFILES WITH ONBOARDING FIELDS
ALTER TABLE public.professional_profiles
    ADD COLUMN IF NOT EXISTS license_state TEXT,
    ADD COLUMN IF NOT EXISTS social_links JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS niche TEXT,
    ADD COLUMN IF NOT EXISTS is_onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE;

-- 2. PROFESSIONAL_INVITES (Managed strictly by ADMIN)
CREATE TABLE IF NOT EXISTS public.professional_invites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL,
    role_id TEXT NOT NULL CHECK (role_id IN ('nutritionist', 'influencer')),
    organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL,
    token_hash TEXT NOT NULL UNIQUE,
    created_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    accepted_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    accepted_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT pg_catalog.timezone('utc', pg_catalog.now())
);

CREATE INDEX IF NOT EXISTS idx_prof_invites_token ON public.professional_invites(token_hash);
CREATE INDEX IF NOT EXISTS idx_prof_invites_email ON public.professional_invites(email);
CREATE INDEX IF NOT EXISTS idx_prof_invites_created_by ON public.professional_invites(created_by);

COMMENT ON TABLE public.professional_invites IS 'Cryptographic invites for Nutritionists and Influencers generated strictly by Admins.';

-- 3. PATIENT_INVITES (Generated by Professionals or Admins)
CREATE TABLE IF NOT EXISTS public.patient_invites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    professional_id UUID NOT NULL REFERENCES public.professional_profiles(id) ON DELETE CASCADE,
    organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL,
    email TEXT,
    token_hash TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'expired', 'revoked')) DEFAULT 'pending',
    expires_at TIMESTAMPTZ NOT NULL,
    accepted_by UUID REFERENCES public.patients(id) ON DELETE SET NULL,
    accepted_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT pg_catalog.timezone('utc', pg_catalog.now())
);

CREATE INDEX IF NOT EXISTS idx_patient_invites_token ON public.patient_invites(token_hash);
CREATE INDEX IF NOT EXISTS idx_patient_invites_prof ON public.patient_invites(professional_id);
CREATE INDEX IF NOT EXISTS idx_patient_invites_status ON public.patient_invites(status);

COMMENT ON TABLE public.patient_invites IS 'Cryptographic invites generated by professionals to link patients safely.';

-- 4. PATIENT_ONBOARDING (Basic general data and primary goal)
CREATE TABLE IF NOT EXISTS public.patient_onboarding (
    id UUID PRIMARY KEY REFERENCES public.patients(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    birth_date DATE,
    gender TEXT CHECK (gender IN ('male', 'female', 'other', 'prefer_not_to_say')),
    height_cm NUMERIC(5,2),
    weight_kg NUMERIC(5,2),
    country TEXT NOT NULL DEFAULT 'BR',
    city TEXT,
    timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
    primary_goal TEXT NOT NULL CHECK (primary_goal IN ('lose_weight', 'gain_muscle', 'maintain_weight', 'improve_health', 'improve_performance')),
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT pg_catalog.timezone('utc', pg_catalog.now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT pg_catalog.timezone('utc', pg_catalog.now())
);

CREATE INDEX IF NOT EXISTS idx_patient_onboarding_goal ON public.patient_onboarding(primary_goal);

COMMENT ON TABLE public.patient_onboarding IS 'General onboarding questionnaire responses for newly linked patients.';

-- ------------------------------------------------------------------------------
-- 5. ENABLE ROW LEVEL SECURITY (RLS)
-- ------------------------------------------------------------------------------
ALTER TABLE public.professional_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_onboarding ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------------------
-- 6. RLS POLICIES FOR PROFESSIONAL_INVITES (Strictly Admin)
-- ------------------------------------------------------------------------------
CREATE POLICY "Admins can view professional invites"
    ON public.professional_invites FOR SELECT
    TO authenticated
    USING (private.is_admin(auth.uid()));

CREATE POLICY "Admins can insert professional invites"
    ON public.professional_invites FOR INSERT
    TO authenticated
    WITH CHECK (private.is_admin(auth.uid()) AND created_by = auth.uid());

CREATE POLICY "Admins can update professional invites"
    ON public.professional_invites FOR UPDATE
    TO authenticated
    USING (private.is_admin(auth.uid()));

CREATE POLICY "Admins can delete professional invites"
    ON public.professional_invites FOR DELETE
    TO authenticated
    USING (private.is_admin(auth.uid()));

-- ------------------------------------------------------------------------------
-- 7. RLS POLICIES FOR PATIENT_INVITES
-- ------------------------------------------------------------------------------
-- Professionals can only view invites they created. Admins can view all. Patients CANNOT view any.
CREATE POLICY "Professionals and Admins can view patient invites"
    ON public.patient_invites FOR SELECT
    TO authenticated
    USING (
        (professional_id = auth.uid() AND private.is_professional(auth.uid()))
        OR private.is_admin(auth.uid())
    );

-- Professionals can insert invites ONLY for themselves. Admins can insert.
CREATE POLICY "Professionals and Admins can insert patient invites"
    ON public.patient_invites FOR INSERT
    TO authenticated
    WITH CHECK (
        (professional_id = auth.uid() AND private.is_professional(auth.uid()))
        OR private.is_admin(auth.uid())
    );

-- Professionals can update/revoke their own invites.
CREATE POLICY "Professionals and Admins can update patient invites"
    ON public.patient_invites FOR UPDATE
    TO authenticated
    USING (
        (professional_id = auth.uid() AND private.is_professional(auth.uid()))
        OR private.is_admin(auth.uid())
    );

-- ------------------------------------------------------------------------------
-- 8. RLS POLICIES FOR PATIENT_ONBOARDING
-- ------------------------------------------------------------------------------
-- Patient views own. Linked active professional views. Admin views.
CREATE POLICY "Patient, linked professional, or admin can view onboarding"
    ON public.patient_onboarding FOR SELECT
    TO authenticated
    USING (
        id = auth.uid()
        OR private.can_access_patient(auth.uid(), id)
        OR private.is_admin(auth.uid())
    );

-- Patient can insert/update their own onboarding.
CREATE POLICY "Patient can insert own onboarding"
    ON public.patient_onboarding FOR INSERT
    TO authenticated
    WITH CHECK (
        id = auth.uid()
        OR private.is_admin(auth.uid())
    );

CREATE POLICY "Patient can update own onboarding"
    ON public.patient_onboarding FOR UPDATE
    TO authenticated
    USING (
        id = auth.uid()
        OR private.is_admin(auth.uid())
    );

-- ------------------------------------------------------------------------------
-- 9. ATOMIC RPC FUNCTION: ACCEPT PATIENT INVITE (Concurrency & Double-Spend Proof)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION private.accept_patient_invite(
    p_token_hash TEXT,
    p_patient_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_invite public.patient_invites%ROWTYPE;
    v_prof_type TEXT;
    v_link_type TEXT;
    v_existing_link_id UUID;
BEGIN
    -- 1. Concurrency lock: row-level lock on the specific invite
    SELECT * INTO v_invite
    FROM public.patient_invites
    WHERE token_hash = p_token_hash
    FOR UPDATE;

    -- 2. Validate invite existence
    IF NOT FOUND THEN
        RAISE EXCEPTION 'INVITE_NOT_FOUND' USING ERRCODE = 'P0002';
    END IF;

    -- 3. Validate revocation
    IF v_invite.revoked_at IS NOT NULL OR v_invite.status = 'revoked' THEN
        RAISE EXCEPTION 'INVITE_REVOKED' USING ERRCODE = 'P0004';
    END IF;

    -- 4. Validate expiration
    IF v_invite.expires_at < pg_catalog.timezone('utc', pg_catalog.now()) OR v_invite.status = 'expired' THEN
        UPDATE public.patient_invites
        SET status = 'expired'
        WHERE id = v_invite.id;
        RAISE EXCEPTION 'INVITE_EXPIRED' USING ERRCODE = 'P0005';
    END IF;

    -- 5. Validate status: MUST be pending
    IF v_invite.status <> 'pending' THEN
        RAISE EXCEPTION 'INVITE_ALREADY_USED_OR_INVALID' USING ERRCODE = 'P0003';
    END IF;

    -- 6. Ensure patient record exists in public.patients
    INSERT INTO public.patients (id)
    VALUES (p_patient_id)
    ON CONFLICT (id) DO NOTHING;

    -- 7. Retrieve professional type to determine link_type safely
    SELECT professional_type INTO v_prof_type
    FROM public.professional_profiles
    WHERE id = v_invite.professional_id;

    IF v_prof_type = 'influencer' THEN
        v_link_type := 'influencer_referral';
    ELSE
        v_link_type := 'direct';
    END IF;

    -- 8. Check if active link already exists between this pair
    SELECT id INTO v_existing_link_id
    FROM public.professional_patient_links
    WHERE professional_id = v_invite.professional_id
      AND patient_id = p_patient_id
      AND status = 'active';

    IF v_existing_link_id IS NULL THEN
        -- Create active primary link
        INSERT INTO public.professional_patient_links (
            professional_id,
            patient_id,
            organization_id,
            is_primary,
            status,
            link_type,
            notes
        ) VALUES (
            v_invite.professional_id,
            p_patient_id,
            v_invite.organization_id,
            TRUE,
            'active',
            v_link_type,
            'Linked via invite ' || v_invite.id::text
        );
    END IF;

    -- 9. Mark invite as accepted (Consumes token atomicity)
    UPDATE public.patient_invites
    SET status = 'accepted',
        accepted_by = p_patient_id,
        accepted_at = pg_catalog.timezone('utc', pg_catalog.now())
    WHERE id = v_invite.id;

    -- 10. Write audit log entry
    INSERT INTO public.audit_logs (
        actor_id,
        action,
        entity_type,
        entity_id,
        organization_id,
        metadata
    ) VALUES (
        p_patient_id,
        'invite.accepted',
        'patient_invites',
        v_invite.id::text,
        v_invite.organization_id,
        jsonb_build_object(
            'professional_id', v_invite.professional_id,
            'link_type', v_link_type,
            'organization_id', v_invite.organization_id
        )
    );

    RETURN jsonb_build_object(
        'success', TRUE,
        'invite_id', v_invite.id,
        'professional_id', v_invite.professional_id,
        'organization_id', v_invite.organization_id,
        'link_type', v_link_type
    );
END;
$$;

-- Grant execution to authenticated role
GRANT EXECUTE ON FUNCTION private.accept_patient_invite(TEXT, UUID) TO authenticated;

-- ------------------------------------------------------------------------------
-- 10. PUBLIC RPC FUNCTION: VALIDATE PATIENT INVITE (Safe Metadata for /invite/[token])
-- ------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION private.validate_patient_invite(
    p_token_hash TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_invite public.patient_invites%ROWTYPE;
    v_prof_name TEXT;
    v_prof_type TEXT;
    v_org_name TEXT;
BEGIN
    SELECT * INTO v_invite
    FROM public.patient_invites
    WHERE token_hash = p_token_hash;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('valid', FALSE, 'reason', 'not_found');
    END IF;

    IF v_invite.revoked_at IS NOT NULL OR v_invite.status = 'revoked' THEN
        RETURN jsonb_build_object('valid', FALSE, 'reason', 'revoked');
    END IF;

    IF v_invite.expires_at < pg_catalog.timezone('utc', pg_catalog.now()) OR v_invite.status = 'expired' THEN
        RETURN jsonb_build_object('valid', FALSE, 'reason', 'expired');
    END IF;

    IF v_invite.status <> 'pending' THEN
        RETURN jsonb_build_object('valid', FALSE, 'reason', 'already_used');
    END IF;

    -- Fetch professional and org details
    SELECT pr.full_name, pp.professional_type
    INTO v_prof_name, v_prof_type
    FROM public.professional_profiles pp
    JOIN public.profiles pr ON pr.id = pp.id
    WHERE pp.id = v_invite.professional_id;

    IF v_invite.organization_id IS NOT NULL THEN
        SELECT name INTO v_org_name
        FROM public.organizations
        WHERE id = v_invite.organization_id;
    END IF;

    RETURN jsonb_build_object(
        'valid', TRUE,
        'professional_name', v_prof_name,
        'professional_type', v_prof_type,
        'organization_name', v_org_name,
        'email', v_invite.email
    );
END;
$$;

GRANT EXECUTE ON FUNCTION private.validate_patient_invite(TEXT) TO anon, authenticated;

-- ------------------------------------------------------------------------------
-- 11. PROFESSIONAL INVITES RPC FUNCTIONS
-- ------------------------------------------------------------------------------

-- Allow system provision flag to bypass immutability trigger for official invite acceptance
CREATE OR REPLACE FUNCTION public.enforce_profile_role_immutability()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    -- If internal system provision flag is active, allow promotion
    IF pg_catalog.current_setting('app.system_role_provision', true) = 'true' THEN
        RETURN NEW;
    END IF;

    -- If role_id is being changed and the actor is not an admin, reject transaction
    IF OLD.role_id IS DISTINCT FROM NEW.role_id THEN
        IF auth.uid() IS NOT NULL AND NOT private.is_admin(auth.uid()) THEN
            RAISE EXCEPTION 'Acesso Negado: A alteração de papéis (roles) é estritamente restrita a administradores.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

-- Validate professional invite token
CREATE OR REPLACE FUNCTION private.validate_professional_invite(
    p_token_hash TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_invite public.professional_invites%ROWTYPE;
    v_org_name TEXT;
BEGIN
    SELECT * INTO v_invite
    FROM public.professional_invites
    WHERE token_hash = p_token_hash;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('valid', FALSE, 'reason', 'not_found');
    END IF;

    IF v_invite.revoked_at IS NOT NULL THEN
        RETURN jsonb_build_object('valid', FALSE, 'reason', 'revoked');
    END IF;

    IF v_invite.expires_at < pg_catalog.timezone('utc', pg_catalog.now()) THEN
        RETURN jsonb_build_object('valid', FALSE, 'reason', 'expired');
    END IF;

    IF v_invite.accepted_at IS NOT NULL THEN
        RETURN jsonb_build_object('valid', FALSE, 'reason', 'already_used');
    END IF;

    IF v_invite.organization_id IS NOT NULL THEN
        SELECT name INTO v_org_name
        FROM public.organizations
        WHERE id = v_invite.organization_id;
    END IF;

    RETURN jsonb_build_object(
        'valid', TRUE,
        'email', v_invite.email,
        'role_id', v_invite.role_id,
        'organization_name', v_org_name
    );
END;
$$;

GRANT EXECUTE ON FUNCTION private.validate_professional_invite(TEXT) TO anon, authenticated;

-- Accept professional invite transactionally
CREATE OR REPLACE FUNCTION private.accept_professional_invite(
    p_token_hash TEXT,
    p_user_id UUID,
    p_full_name TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_invite public.professional_invites%ROWTYPE;
BEGIN
    SELECT * INTO v_invite
    FROM public.professional_invites
    WHERE token_hash = p_token_hash
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'INVITE_NOT_FOUND' USING ERRCODE = 'P0002';
    END IF;

    IF v_invite.accepted_at IS NOT NULL THEN
        RAISE EXCEPTION 'INVITE_ALREADY_USED' USING ERRCODE = 'P0003';
    END IF;

    IF v_invite.revoked_at IS NOT NULL THEN
        RAISE EXCEPTION 'INVITE_REVOKED' USING ERRCODE = 'P0004';
    END IF;

    IF v_invite.expires_at < pg_catalog.timezone('utc', pg_catalog.now()) THEN
        RAISE EXCEPTION 'INVITE_EXPIRED' USING ERRCODE = 'P0005';
    END IF;

    -- Enable system provision flag locally for this transaction
    PERFORM pg_catalog.set_config('app.system_role_provision', 'true', true);

    -- Update profile role to exact invited role
    UPDATE public.profiles
    SET role_id = v_invite.role_id,
        full_name = COALESCE(NULLIF(TRIM(p_full_name), ''), full_name)
    WHERE id = p_user_id;

    -- Delete dummy patient record if it was auto-created by auth trigger
    DELETE FROM public.patients WHERE id = p_user_id;

    -- Ensure professional profile exists
    INSERT INTO public.professional_profiles (id, professional_type)
    VALUES (p_user_id, v_invite.role_id)
    ON CONFLICT (id) DO UPDATE SET professional_type = EXCLUDED.professional_type;

    -- If org is specified, add as member
    IF v_invite.organization_id IS NOT NULL THEN
        INSERT INTO public.organization_members (organization_id, user_id, role_in_org)
        VALUES (v_invite.organization_id, p_user_id, 'member')
        ON CONFLICT (organization_id, user_id) DO NOTHING;
    END IF;

    -- Mark invite as accepted
    UPDATE public.professional_invites
    SET accepted_by = p_user_id,
        accepted_at = pg_catalog.timezone('utc', pg_catalog.now())
    WHERE id = v_invite.id;

    -- Reset provision flag
    PERFORM pg_catalog.set_config('app.system_role_provision', 'false', true);

    -- Audit log
    INSERT INTO public.audit_logs (
        actor_id,
        action,
        entity_type,
        entity_id,
        organization_id,
        metadata
    ) VALUES (
        p_user_id,
        'professional_invite.accepted',
        'professional_invites',
        v_invite.id::text,
        v_invite.organization_id,
        jsonb_build_object('role_id', v_invite.role_id, 'email', v_invite.email)
    );

    RETURN jsonb_build_object(
        'success', TRUE,
        'role_id', v_invite.role_id,
        'organization_id', v_invite.organization_id
    );
END;
$$;

GRANT EXECUTE ON FUNCTION private.accept_professional_invite(TEXT, UUID, TEXT) TO authenticated;

